services:
  app:
    image: ipz215kvv/swe304
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=swe304
    env_file:
      - .env

  db:
    image: mysql:8.0-oracle
    command: ["--default-authentication-plugin=mysql_native_password", "--skip-log-bin"]
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=swe304
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
  db-data:
